services:
  app:
    image: golang:1.24.1
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    restart: unless-stopped

  db:
    image: postgres:latest
    expose:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s  