name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-test:
    name: Lint, Test, and Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Dependencies
        run: go mod tidy

      - name: Lint Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out
          fail_ci_if_error: true

      - name: Run Security Check
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...

  build:
    name: Build Application
    needs: lint-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build Binary
        run: go build -o noteflow .
